### ISSUE TITLE
Shape for conversion.py

### ISSUE THREAD

**Issue by johnbritto15** [BINDS-LAB-UMASS/bindsnet#2]
I used the conversion.py with the code 

ann = Net()
snn= ann_to_snn(ann, input_shape=(128,3,32,32))

And I get the error

AssertionError: Target dimensionality must be (out_channels, ?,(input_height - filter_height + 2 * padding_height) / stride_height + 1,(input_width - filter_width + 2 * padding_width) / stride_width + 1

It's on line 287 of the network/topology.py code. Is this an issue with my input? How exactly do the input and target dimensions look like and how could I ensure my input format is consistent with what's needed?

**Comment by djsaunde** [comment]
Hi @johnbritto15,

What code are you using that produces this error? Could you please share it?

**Comment by dee0512** [comment]
#8
